mixed-port: 7890
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
ipv6: false

proxy-providers:
  vlv:
    type: http
    url: "__PROXY_SUB_URL__"
    interval: 3600
    path: ./providers/vlv.yaml
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 5000

proxy-groups:
  - name: PROXY
    type: url-test
    use:
      - vlv
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 150

rules:
  - MATCH,PROXY
